# -*- coding: utf-8 -*-
"""NIDS_Backend_API.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cQYEVboxQ_0I0OTUmkc9Nhy4UQWxmoZF
"""

"""API Sunucusunu Hazırlama ve Çalıştırma"""

import joblib
import pandas as pd
import numpy as np
import threading
import logging
import warnings
import time
from flask import Flask, request, jsonify, make_response
from flask_cors import CORS
from flask_socketio import SocketIO, emit
from pyngrok import ngrok
from scapy.all import sniff, IP, TCP, UDP

#log temizliği
logging.getLogger('werkzeug').setLevel(logging.ERROR)
logging.getLogger('socketio').setLevel(logging.ERROR)
logging.getLogger('engineio').setLevel(logging.ERROR)
warnings.filterwarnings('ignore')

# INITIALIZATION
app = Flask(__name__)
CORS(app, resources={r"/*": {"origins": "*"}}, supports_credentials=True)
socketio = SocketIO(app, cors_allowed_origins="*", async_mode='eventlet', logger=False, engineio_logger=False)

#Dosya Yolları
MODEL_FILE = "./models/nids_model_v2.pkl"
SCALER_FILE = "./models/nids_scaler_v2.pkl"
FEATURES_FILE = "./models/nids_top_features.pkl"
ALL_COLUMNS_FILE = "./models/nids_all_columns.pkl"
NUMERIC_COLS_FILE = "./models/nids_numeric_cols.pkl"
MAPPING_FILE = "./models/nids_inverse_mapping.pkl"

#load pipleine components
try:
    model = joblib.load(MODEL_FILE)
    scaler = joblib.load(SCALER_FILE)
    top_features = joblib.load(FEATURES_FILE)
    all_columns = joblib.load(ALL_COLUMNS_FILE)
    numeric_cols = joblib.load(NUMERIC_COLS_FILE)
    inverse_mapping = joblib.load(MAPPING_FILE)
    print("✅ Sistem Hazır.")
except Exception as e:
    print(f"❌ Yükleme Hatası: {str(e)}")

# Trafik yoğunluğunu ölçmek için basit bir sayaç
traffic_stats = {"packet_count": 0, "last_reset": time.time()}

def network_traffic_validator(packet, ml_prediction):
    """
    Modelin sonucunu ağın fiziksel gerçekliğiyle doğrular.
    """
    global traffic_stats
    current_time = time.time()
    packet_size = len(packet)

    # 1 saniyede bir sayacı sıfırla
    if current_time - traffic_stats["last_reset"] > 1.0:
        traffic_stats["packet_count"] = 0
        traffic_stats["last_reset"] = current_time

    traffic_stats["packet_count"] += 1

    # DOĞRULAMA MANTIĞI:
    if ml_prediction == 'DOS':
        if traffic_stats["packet_count"] < 50 and packet_size < 1500:
            return 'NORMAL'

    return ml_prediction

#core preprocessing
def preprocess_pipeline(raw_df, apply_scaling=True):
    full_df = pd.DataFrame(0, index=np.arange(len(raw_df)), columns=all_columns)
    for col in raw_df.columns:
        str_col = str(col)
        if str_col in full_df.columns:
            full_df[str_col] = raw_df[col]
    if apply_scaling:
        full_df[numeric_cols] = scaler.transform(full_df[numeric_cols])
    final_features = [str(f) for f in top_features]
    return full_df[final_features]

#real time sniffer
def real_time_sniffer():
    def process_packet(packet):
        if IP in packet:
            src_bytes = len(packet)
            is_http = 1.0 if packet.haslayer(TCP) and (packet[TCP].dport == 80 or packet[TCP].sport == 80) else 0.0
            is_ftp = 1.0 if packet.haslayer(TCP) and (packet[TCP].dport == 21 or packet[TCP].sport == 21) else 0.0

            live_payload = {"4": src_bytes, "5": 0.0, "32": 1.0, "34": 0.0, "11": 0.0, "37": 0.0, "2_http": is_http, "23": 0.01, "35": 0.0, "22": 0.01, "0": 0.0, "33": 1.0, "31": 1.0, "9": 0.0, "2_ftp_data": is_ftp, "29": 0.0, "36": 0.0, "3_S0": 0.0, "24": 0.0, "25": 0.0}

            df_incoming = pd.DataFrame([live_payload])
            processed = preprocess_pipeline(df_incoming, apply_scaling=True)
            prediction_id = int(model.predict(processed)[0])
            ml_result = inverse_mapping[prediction_id]

            final_result = network_traffic_validator(packet, ml_result)

            if final_result != 'NORMAL':
                print(f"🚨 ATAK TESPİTİ (Onaylandı): {final_result} - Hedef IP: {packet[IP].dst}")
                socketio.emit('live_threat_alert', {
                    'prediction': final_result,
                    'details': f"IP: {packet[IP].src} -> {packet[IP].dst} | Filtre: Ağ Analizcisi Onaylı"
                })

    print("📡 Sniffer Aktif: Hibrit Analiz Modu (ML + Ağ Kuralları)")
    sniff(filter="tcp or udp", prn=process_packet, store=False)

sniffer_thread = threading.Thread(target=real_time_sniffer, daemon=True)
sniffer_thread.start()

#rest endpoints
@app.route('/predict_file', methods=['POST', 'OPTIONS'])
def predict_file():
    if request.method == 'OPTIONS': return make_response()
    try:
        file = request.files['file']
        df_upload = pd.read_csv(file)
        df_upload.columns = df_upload.columns.astype(str).str.strip()
        existing_numeric = [c for c in numeric_cols if c in df_upload.columns]
        is_already_scaled = df_upload[existing_numeric].max().max() <= 1.0 if existing_numeric else False
        processed = preprocess_pipeline(df_upload, apply_scaling=not is_already_scaled)
        predictions = model.predict(processed)
        labels = [inverse_mapping[int(p)] for p in predictions]
        output = {'total': len(labels), 'attacks': sum(1 for L in labels if L != 'NORMAL'), 'details': pd.Series(labels).value_counts().to_dict(), 'status': 'success'}
        print(f"\n📁 DOSYA ANALİZİ: {output}\n")
        res = jsonify(output)
        res.headers.add("ngrok-skip-browser-warning", "true")
        return res
    except Exception as e: return jsonify({'status': 'error', 'message': str(e)}), 500

@app.route('/predict', methods=['POST'])
def predict():
    try:
        incoming_data = request.json
        df_incoming = pd.DataFrame([incoming_data])
        processed = preprocess_pipeline(df_incoming, apply_scaling=False)
        raw_prediction = model.predict(processed)
        result_label = inverse_mapping.get(int(raw_prediction[0]), "Bilinmeyen")
        output = {'status': 'success', 'prediction': result_label}
        print(f"\n🎯 MANUEL TAHMİN: {output}\n")
        res = jsonify(output)
        res.headers.add("ngrok-skip-browser-warning", "true")
        return res
    except Exception as e: return jsonify({'status': 'error', 'message': str(e)}), 500

if __name__ == '__main__':
    try:
        ngrok.set_auth_token("3D7JZUckeG2JUoREzVQjKxlZsl4_6oLVRvh5drAMKDhyeJujQ")
        public_url = ngrok.connect(5000)
        print(f"\n🚀 ENGINE ONLINE | HİBRİT ANALİZ AKTİF")
        print(f"🔗 LİNK: {public_url.public_url}\n")
        socketio.run(app, port=5000, allow_unsafe_werkzeug=True)
    except Exception as e: print(f"❌ Hata: {e}")